<?php

namespace Database\Seeders;

use App\Models\AffiliateLink;
use App\Models\Country;
use App\Models\Operator;
use Illuminate\Database\Seeder;

class InitialDataSeeder extends Seeder
{
    public function run(): void
    {
        $countries = $this->getAllCountries();

        foreach ($countries as $country) {
            Country::create($country);
        }

        $operators = [
            [
                'name' => 'Bet365',
                'slug' => 'bet365',
                'status' => 'active',
                'default_url' => 'https://www.bet365.com',
            ],
            [
                'name' => 'William Hill',
                'slug' => 'william-hill',
                'status' => 'active',
                'default_url' => 'https://www.williamhill.com',
            ],
            [
                'name' => 'Unibet',
                'slug' => 'unibet',
                'status' => 'active',
                'default_url' => 'https://www.unibet.com',
            ],
        ];

        foreach ($operators as $operatorData) {
            $operator = Operator::create($operatorData);

            $france = Country::where('iso_code', 'FR')->first();
            if ($france) {
                AffiliateLink::create([
                    'operator_id' => $operator->id,
                    'country_id' => $france->id,
                    'url' => $operatorData['default_url'] . '/fr?aff=12345',
                    'status' => 'active',
                    'priority' => 10,
                ]);
            }

            $uk = Country::where('iso_code', 'GB')->first();
            if ($uk) {
                AffiliateLink::create([
                    'operator_id' => $operator->id,
                    'country_id' => $uk->id,
                    'url' => $operatorData['default_url'] . '/uk?aff=12345',
                    'status' => 'active',
                    'priority' => 10,
                ]);
            }
        }

        $this->command->info('Initial data seeded successfully!');
    }

    private function getAllCountries(): array
    {
        return [
            ['iso_code' => 'AD', 'name' => 'Andorra', 'status' => 'active'],
            ['iso_code' => 'AE', 'name' => 'United Arab Emirates', 'status' => 'active'],
            ['iso_code' => 'AF', 'name' => 'Afghanistan', 'status' => 'active'],
            ['iso_code' => 'AG', 'name' => 'Antigua and Barbuda', 'status' => 'active'],
            ['iso_code' => 'AI', 'name' => 'Anguilla', 'status' => 'active'],
            ['iso_code' => 'AL', 'name' => 'Albania', 'status' => 'active'],
            ['iso_code' => 'AM', 'name' => 'Armenia', 'status' => 'active'],
            ['iso_code' => 'AO', 'name' => 'Angola', 'status' => 'active'],
            ['iso_code' => 'AQ', 'name' => 'Antarctica', 'status' => 'active'],
            ['iso_code' => 'AR', 'name' => 'Argentina', 'status' => 'active'],
            ['iso_code' => 'AS', 'name' => 'American Samoa', 'status' => 'active'],
            ['iso_code' => 'AT', 'name' => 'Austria', 'status' => 'active'],
            ['iso_code' => 'AU', 'name' => 'Australia', 'status' => 'active'],
            ['iso_code' => 'AW', 'name' => 'Aruba', 'status' => 'active'],
            ['iso_code' => 'AX', 'name' => 'Åland Islands', 'status' => 'active'],
            ['iso_code' => 'AZ', 'name' => 'Azerbaijan', 'status' => 'active'],
            ['iso_code' => 'BA', 'name' => 'Bosnia and Herzegovina', 'status' => 'active'],
            ['iso_code' => 'BB', 'name' => 'Barbados', 'status' => 'active'],
            ['iso_code' => 'BD', 'name' => 'Bangladesh', 'status' => 'active'],
            ['iso_code' => 'BE', 'name' => 'Belgium', 'status' => 'active'],
            ['iso_code' => 'BF', 'name' => 'Burkina Faso', 'status' => 'active'],
            ['iso_code' => 'BG', 'name' => 'Bulgaria', 'status' => 'active'],
            ['iso_code' => 'BH', 'name' => 'Bahrain', 'status' => 'active'],
            ['iso_code' => 'BI', 'name' => 'Burundi', 'status' => 'active'],
            ['iso_code' => 'BJ', 'name' => 'Benin', 'status' => 'active'],
            ['iso_code' => 'BL', 'name' => 'Saint Barthélemy', 'status' => 'active'],
            ['iso_code' => 'BM', 'name' => 'Bermuda', 'status' => 'active'],
            ['iso_code' => 'BN', 'name' => 'Brunei', 'status' => 'active'],
            ['iso_code' => 'BO', 'name' => 'Bolivia', 'status' => 'active'],
            ['iso_code' => 'BQ', 'name' => 'Caribbean Netherlands', 'status' => 'active'],
            ['iso_code' => 'BR', 'name' => 'Brazil', 'status' => 'active'],
            ['iso_code' => 'BS', 'name' => 'Bahamas', 'status' => 'active'],
            ['iso_code' => 'BT', 'name' => 'Bhutan', 'status' => 'active'],
            ['iso_code' => 'BV', 'name' => 'Bouvet Island', 'status' => 'active'],
            ['iso_code' => 'BW', 'name' => 'Botswana', 'status' => 'active'],
            ['iso_code' => 'BY', 'name' => 'Belarus', 'status' => 'active'],
            ['iso_code' => 'BZ', 'name' => 'Belize', 'status' => 'active'],
            ['iso_code' => 'CA', 'name' => 'Canada', 'status' => 'active'],
            ['iso_code' => 'CC', 'name' => 'Cocos Islands', 'status' => 'active'],
            ['iso_code' => 'CD', 'name' => 'Democratic Republic of the Congo', 'status' => 'active'],
            ['iso_code' => 'CF', 'name' => 'Central African Republic', 'status' => 'active'],
            ['iso_code' => 'CG', 'name' => 'Republic of the Congo', 'status' => 'active'],
            ['iso_code' => 'CH', 'name' => 'Switzerland', 'status' => 'active'],
            ['iso_code' => 'CI', 'name' => 'Ivory Coast', 'status' => 'active'],
            ['iso_code' => 'CK', 'name' => 'Cook Islands', 'status' => 'active'],
            ['iso_code' => 'CL', 'name' => 'Chile', 'status' => 'active'],
            ['iso_code' => 'CM', 'name' => 'Cameroon', 'status' => 'active'],
            ['iso_code' => 'CN', 'name' => 'China', 'status' => 'active'],
            ['iso_code' => 'CO', 'name' => 'Colombia', 'status' => 'active'],
            ['iso_code' => 'CR', 'name' => 'Costa Rica', 'status' => 'active'],
            ['iso_code' => 'CU', 'name' => 'Cuba', 'status' => 'active'],
            ['iso_code' => 'CV', 'name' => 'Cape Verde', 'status' => 'active'],
            ['iso_code' => 'CW', 'name' => 'Curaçao', 'status' => 'active'],
            ['iso_code' => 'CX', 'name' => 'Christmas Island', 'status' => 'active'],
            ['iso_code' => 'CY', 'name' => 'Cyprus', 'status' => 'active'],
            ['iso_code' => 'CZ', 'name' => 'Czech Republic', 'status' => 'active'],
            ['iso_code' => 'DE', 'name' => 'Germany', 'status' => 'active'],
            ['iso_code' => 'DJ', 'name' => 'Djibouti', 'status' => 'active'],
            ['iso_code' => 'DK', 'name' => 'Denmark', 'status' => 'active'],
            ['iso_code' => 'DM', 'name' => 'Dominica', 'status' => 'active'],
            ['iso_code' => 'DO', 'name' => 'Dominican Republic', 'status' => 'active'],
            ['iso_code' => 'DZ', 'name' => 'Algeria', 'status' => 'active'],
            ['iso_code' => 'EC', 'name' => 'Ecuador', 'status' => 'active'],
            ['iso_code' => 'EE', 'name' => 'Estonia', 'status' => 'active'],
            ['iso_code' => 'EG', 'name' => 'Egypt', 'status' => 'active'],
            ['iso_code' => 'EH', 'name' => 'Western Sahara', 'status' => 'active'],
            ['iso_code' => 'ER', 'name' => 'Eritrea', 'status' => 'active'],
            ['iso_code' => 'ES', 'name' => 'Spain', 'status' => 'active'],
            ['iso_code' => 'ET', 'name' => 'Ethiopia', 'status' => 'active'],
            ['iso_code' => 'FI', 'name' => 'Finland', 'status' => 'active'],
            ['iso_code' => 'FJ', 'name' => 'Fiji', 'status' => 'active'],
            ['iso_code' => 'FK', 'name' => 'Falkland Islands', 'status' => 'active'],
            ['iso_code' => 'FM', 'name' => 'Micronesia', 'status' => 'active'],
            ['iso_code' => 'FO', 'name' => 'Faroe Islands', 'status' => 'active'],
            ['iso_code' => 'FR', 'name' => 'France', 'status' => 'active'],
            ['iso_code' => 'GA', 'name' => 'Gabon', 'status' => 'active'],
            ['iso_code' => 'GB', 'name' => 'United Kingdom', 'status' => 'active'],
            ['iso_code' => 'GD', 'name' => 'Grenada', 'status' => 'active'],
            ['iso_code' => 'GE', 'name' => 'Georgia', 'status' => 'active'],
            ['iso_code' => 'GF', 'name' => 'French Guiana', 'status' => 'active'],
            ['iso_code' => 'GG', 'name' => 'Guernsey', 'status' => 'active'],
            ['iso_code' => 'GH', 'name' => 'Ghana', 'status' => 'active'],
            ['iso_code' => 'GI', 'name' => 'Gibraltar', 'status' => 'active'],
            ['iso_code' => 'GL', 'name' => 'Greenland', 'status' => 'active'],
            ['iso_code' => 'GM', 'name' => 'Gambia', 'status' => 'active'],
            ['iso_code' => 'GN', 'name' => 'Guinea', 'status' => 'active'],
            ['iso_code' => 'GP', 'name' => 'Guadeloupe', 'status' => 'active'],
            ['iso_code' => 'GQ', 'name' => 'Equatorial Guinea', 'status' => 'active'],
            ['iso_code' => 'GR', 'name' => 'Greece', 'status' => 'active'],
            ['iso_code' => 'GS', 'name' => 'South Georgia and the South Sandwich Islands', 'status' => 'active'],
            ['iso_code' => 'GT', 'name' => 'Guatemala', 'status' => 'active'],
            ['iso_code' => 'GU', 'name' => 'Guam', 'status' => 'active'],
            ['iso_code' => 'GW', 'name' => 'Guinea-Bissau', 'status' => 'active'],
            ['iso_code' => 'GY', 'name' => 'Guyana', 'status' => 'active'],
            ['iso_code' => 'HK', 'name' => 'Hong Kong', 'status' => 'active'],
            ['iso_code' => 'HM', 'name' => 'Heard Island and McDonald Islands', 'status' => 'active'],
            ['iso_code' => 'HN', 'name' => 'Honduras', 'status' => 'active'],
            ['iso_code' => 'HR', 'name' => 'Croatia', 'status' => 'active'],
            ['iso_code' => 'HT', 'name' => 'Haiti', 'status' => 'active'],
            ['iso_code' => 'HU', 'name' => 'Hungary', 'status' => 'active'],
            ['iso_code' => 'ID', 'name' => 'Indonesia', 'status' => 'active'],
            ['iso_code' => 'IE', 'name' => 'Ireland', 'status' => 'active'],
            ['iso_code' => 'IL', 'name' => 'Israel', 'status' => 'active'],
            ['iso_code' => 'IM', 'name' => 'Isle of Man', 'status' => 'active'],
            ['iso_code' => 'IN', 'name' => 'India', 'status' => 'active'],
            ['iso_code' => 'IO', 'name' => 'British Indian Ocean Territory', 'status' => 'active'],
            ['iso_code' => 'IQ', 'name' => 'Iraq', 'status' => 'active'],
            ['iso_code' => 'IR', 'name' => 'Iran', 'status' => 'active'],
            ['iso_code' => 'IS', 'name' => 'Iceland', 'status' => 'active'],
            ['iso_code' => 'IT', 'name' => 'Italy', 'status' => 'active'],
            ['iso_code' => 'JE', 'name' => 'Jersey', 'status' => 'active'],
            ['iso_code' => 'JM', 'name' => 'Jamaica', 'status' => 'active'],
            ['iso_code' => 'JO', 'name' => 'Jordan', 'status' => 'active'],
            ['iso_code' => 'JP', 'name' => 'Japan', 'status' => 'active'],
            ['iso_code' => 'KE', 'name' => 'Kenya', 'status' => 'active'],
            ['iso_code' => 'KG', 'name' => 'Kyrgyzstan', 'status' => 'active'],
            ['iso_code' => 'KH', 'name' => 'Cambodia', 'status' => 'active'],
            ['iso_code' => 'KI', 'name' => 'Kiribati', 'status' => 'active'],
            ['iso_code' => 'KM', 'name' => 'Comoros', 'status' => 'active'],
            ['iso_code' => 'KN', 'name' => 'Saint Kitts and Nevis', 'status' => 'active'],
            ['iso_code' => 'KP', 'name' => 'North Korea', 'status' => 'active'],
            ['iso_code' => 'KR', 'name' => 'South Korea', 'status' => 'active'],
            ['iso_code' => 'KW', 'name' => 'Kuwait', 'status' => 'active'],
            ['iso_code' => 'KY', 'name' => 'Cayman Islands', 'status' => 'active'],
            ['iso_code' => 'KZ', 'name' => 'Kazakhstan', 'status' => 'active'],
            ['iso_code' => 'LA', 'name' => 'Laos', 'status' => 'active'],
            ['iso_code' => 'LB', 'name' => 'Lebanon', 'status' => 'active'],
            ['iso_code' => 'LC', 'name' => 'Saint Lucia', 'status' => 'active'],
            ['iso_code' => 'LI', 'name' => 'Liechtenstein', 'status' => 'active'],
            ['iso_code' => 'LK', 'name' => 'Sri Lanka', 'status' => 'active'],
            ['iso_code' => 'LR', 'name' => 'Liberia', 'status' => 'active'],
            ['iso_code' => 'LS', 'name' => 'Lesotho', 'status' => 'active'],
            ['iso_code' => 'LT', 'name' => 'Lithuania', 'status' => 'active'],
            ['iso_code' => 'LU', 'name' => 'Luxembourg', 'status' => 'active'],
            ['iso_code' => 'LV', 'name' => 'Latvia', 'status' => 'active'],
            ['iso_code' => 'LY', 'name' => 'Libya', 'status' => 'active'],
            ['iso_code' => 'MA', 'name' => 'Morocco', 'status' => 'active'],
            ['iso_code' => 'MC', 'name' => 'Monaco', 'status' => 'active'],
            ['iso_code' => 'MD', 'name' => 'Moldova', 'status' => 'active'],
            ['iso_code' => 'ME', 'name' => 'Montenegro', 'status' => 'active'],
            ['iso_code' => 'MF', 'name' => 'Saint Martin', 'status' => 'active'],
            ['iso_code' => 'MG', 'name' => 'Madagascar', 'status' => 'active'],
            ['iso_code' => 'MH', 'name' => 'Marshall Islands', 'status' => 'active'],
            ['iso_code' => 'MK', 'name' => 'North Macedonia', 'status' => 'active'],
            ['iso_code' => 'ML', 'name' => 'Mali', 'status' => 'active'],
            ['iso_code' => 'MM', 'name' => 'Myanmar', 'status' => 'active'],
            ['iso_code' => 'MN', 'name' => 'Mongolia', 'status' => 'active'],
            ['iso_code' => 'MO', 'name' => 'Macau', 'status' => 'active'],
            ['iso_code' => 'MP', 'name' => 'Northern Mariana Islands', 'status' => 'active'],
            ['iso_code' => 'MQ', 'name' => 'Martinique', 'status' => 'active'],
            ['iso_code' => 'MR', 'name' => 'Mauritania', 'status' => 'active'],
            ['iso_code' => 'MS', 'name' => 'Montserrat', 'status' => 'active'],
            ['iso_code' => 'MT', 'name' => 'Malta', 'status' => 'active'],
            ['iso_code' => 'MU', 'name' => 'Mauritius', 'status' => 'active'],
            ['iso_code' => 'MV', 'name' => 'Maldives', 'status' => 'active'],
            ['iso_code' => 'MW', 'name' => 'Malawi', 'status' => 'active'],
            ['iso_code' => 'MX', 'name' => 'Mexico', 'status' => 'active'],
            ['iso_code' => 'MY', 'name' => 'Malaysia', 'status' => 'active'],
            ['iso_code' => 'MZ', 'name' => 'Mozambique', 'status' => 'active'],
            ['iso_code' => 'NA', 'name' => 'Namibia', 'status' => 'active'],
            ['iso_code' => 'NC', 'name' => 'New Caledonia', 'status' => 'active'],
            ['iso_code' => 'NE', 'name' => 'Niger', 'status' => 'active'],
            ['iso_code' => 'NF', 'name' => 'Norfolk Island', 'status' => 'active'],
            ['iso_code' => 'NG', 'name' => 'Nigeria', 'status' => 'active'],
            ['iso_code' => 'NI', 'name' => 'Nicaragua', 'status' => 'active'],
            ['iso_code' => 'NL', 'name' => 'Netherlands', 'status' => 'active'],
            ['iso_code' => 'NO', 'name' => 'Norway', 'status' => 'active'],
            ['iso_code' => 'NP', 'name' => 'Nepal', 'status' => 'active'],
            ['iso_code' => 'NR', 'name' => 'Nauru', 'status' => 'active'],
            ['iso_code' => 'NU', 'name' => 'Niue', 'status' => 'active'],
            ['iso_code' => 'NZ', 'name' => 'New Zealand', 'status' => 'active'],
            ['iso_code' => 'OM', 'name' => 'Oman', 'status' => 'active'],
            ['iso_code' => 'PA', 'name' => 'Panama', 'status' => 'active'],
            ['iso_code' => 'PE', 'name' => 'Peru', 'status' => 'active'],
            ['iso_code' => 'PF', 'name' => 'French Polynesia', 'status' => 'active'],
            ['iso_code' => 'PG', 'name' => 'Papua New Guinea', 'status' => 'active'],
            ['iso_code' => 'PH', 'name' => 'Philippines', 'status' => 'active'],
            ['iso_code' => 'PK', 'name' => 'Pakistan', 'status' => 'active'],
            ['iso_code' => 'PL', 'name' => 'Poland', 'status' => 'active'],
            ['iso_code' => 'PM', 'name' => 'Saint Pierre and Miquelon', 'status' => 'active'],
            ['iso_code' => 'PN', 'name' => 'Pitcairn Islands', 'status' => 'active'],
            ['iso_code' => 'PR', 'name' => 'Puerto Rico', 'status' => 'active'],
            ['iso_code' => 'PS', 'name' => 'Palestine', 'status' => 'active'],
            ['iso_code' => 'PT', 'name' => 'Portugal', 'status' => 'active'],
            ['iso_code' => 'PW', 'name' => 'Palau', 'status' => 'active'],
            ['iso_code' => 'PY', 'name' => 'Paraguay', 'status' => 'active'],
            ['iso_code' => 'QA', 'name' => 'Qatar', 'status' => 'active'],
            ['iso_code' => 'RE', 'name' => 'Réunion', 'status' => 'active'],
            ['iso_code' => 'RO', 'name' => 'Romania', 'status' => 'active'],
            ['iso_code' => 'RS', 'name' => 'Serbia', 'status' => 'active'],
            ['iso_code' => 'RU', 'name' => 'Russia', 'status' => 'active'],
            ['iso_code' => 'RW', 'name' => 'Rwanda', 'status' => 'active'],
            ['iso_code' => 'SA', 'name' => 'Saudi Arabia', 'status' => 'active'],
            ['iso_code' => 'SB', 'name' => 'Solomon Islands', 'status' => 'active'],
            ['iso_code' => 'SC', 'name' => 'Seychelles', 'status' => 'active'],
            ['iso_code' => 'SD', 'name' => 'Sudan', 'status' => 'active'],
            ['iso_code' => 'SE', 'name' => 'Sweden', 'status' => 'active'],
            ['iso_code' => 'SG', 'name' => 'Singapore', 'status' => 'active'],
            ['iso_code' => 'SH', 'name' => 'Saint Helena, Ascension and Tristan da Cunha', 'status' => 'active'],
            ['iso_code' => 'SI', 'name' => 'Slovenia', 'status' => 'active'],
            ['iso_code' => 'SJ', 'name' => 'Svalbard and Jan Mayen', 'status' => 'active'],
            ['iso_code' => 'SK', 'name' => 'Slovakia', 'status' => 'active'],
            ['iso_code' => 'SL', 'name' => 'Sierra Leone', 'status' => 'active'],
            ['iso_code' => 'SM', 'name' => 'San Marino', 'status' => 'active'],
            ['iso_code' => 'SN', 'name' => 'Senegal', 'status' => 'active'],
            ['iso_code' => 'SO', 'name' => 'Somalia', 'status' => 'active'],
            ['iso_code' => 'SR', 'name' => 'Suriname', 'status' => 'active'],
            ['iso_code' => 'SS', 'name' => 'South Sudan', 'status' => 'active'],
            ['iso_code' => 'ST', 'name' => 'São Tomé and Príncipe', 'status' => 'active'],
            ['iso_code' => 'SV', 'name' => 'El Salvador', 'status' => 'active'],
            ['iso_code' => 'SX', 'name' => 'Sint Maarten', 'status' => 'active'],
            ['iso_code' => 'SY', 'name' => 'Syria', 'status' => 'active'],
            ['iso_code' => 'SZ', 'name' => 'Eswatini', 'status' => 'active'],
            ['iso_code' => 'TC', 'name' => 'Turks and Caicos Islands', 'status' => 'active'],
            ['iso_code' => 'TD', 'name' => 'Chad', 'status' => 'active'],
            ['iso_code' => 'TF', 'name' => 'French Southern and Antarctic Lands', 'status' => 'active'],
            ['iso_code' => 'TG', 'name' => 'Togo', 'status' => 'active'],
            ['iso_code' => 'TH', 'name' => 'Thailand', 'status' => 'active'],
            ['iso_code' => 'TJ', 'name' => 'Tajikistan', 'status' => 'active'],
            ['iso_code' => 'TK', 'name' => 'Tokelau', 'status' => 'active'],
            ['iso_code' => 'TL', 'name' => 'East Timor', 'status' => 'active'],
            ['iso_code' => 'TM', 'name' => 'Turkmenistan', 'status' => 'active'],
            ['iso_code' => 'TN', 'name' => 'Tunisia', 'status' => 'active'],
            ['iso_code' => 'TO', 'name' => 'Tonga', 'status' => 'active'],
            ['iso_code' => 'TR', 'name' => 'Turkey', 'status' => 'active'],
            ['iso_code' => 'TT', 'name' => 'Trinidad and Tobago', 'status' => 'active'],
            ['iso_code' => 'TV', 'name' => 'Tuvalu', 'status' => 'active'],
            ['iso_code' => 'TW', 'name' => 'Taiwan', 'status' => 'active'],
            ['iso_code' => 'TZ', 'name' => 'Tanzania', 'status' => 'active'],
            ['iso_code' => 'UA', 'name' => 'Ukraine', 'status' => 'active'],
            ['iso_code' => 'UG', 'name' => 'Uganda', 'status' => 'active'],
            ['iso_code' => 'UM', 'name' => 'United States Minor Outlying Islands', 'status' => 'active'],
            ['iso_code' => 'US', 'name' => 'United States', 'status' => 'active'],
            ['iso_code' => 'UY', 'name' => 'Uruguay', 'status' => 'active'],
            ['iso_code' => 'UZ', 'name' => 'Uzbekistan', 'status' => 'active'],
            ['iso_code' => 'VA', 'name' => 'Vatican City', 'status' => 'active'],
            ['iso_code' => 'VC', 'name' => 'Saint Vincent and the Grenadines', 'status' => 'active'],
            ['iso_code' => 'VE', 'name' => 'Venezuela', 'status' => 'active'],
            ['iso_code' => 'VG', 'name' => 'British Virgin Islands', 'status' => 'active'],
            ['iso_code' => 'VI', 'name' => 'United States Virgin Islands', 'status' => 'active'],
            ['iso_code' => 'VN', 'name' => 'Vietnam', 'status' => 'active'],
            ['iso_code' => 'VU', 'name' => 'Vanuatu', 'status' => 'active'],
            ['iso_code' => 'WF', 'name' => 'Wallis and Futuna', 'status' => 'active'],
            ['iso_code' => 'WS', 'name' => 'Samoa', 'status' => 'active'],
            ['iso_code' => 'YE', 'name' => 'Yemen', 'status' => 'active'],
            ['iso_code' => 'YT', 'name' => 'Mayotte', 'status' => 'active'],
            ['iso_code' => 'ZA', 'name' => 'South Africa', 'status' => 'active'],
            ['iso_code' => 'ZM', 'name' => 'Zambia', 'status' => 'active'],
            ['iso_code' => 'ZW', 'name' => 'Zimbabwe', 'status' => 'active'],
        ];
    }
}